apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-service-account
  namespace: nekazari
  labels:
    app: keycloak

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-role
  namespace: nekazari
  labels:
    app: keycloak
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-role-binding
  namespace: nekazari
  labels:
    app: keycloak
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak-role
subjects:
  - kind: ServiceAccount
    name: keycloak-service-account
    namespace: nekazari
